### ISSUE TITLE
Favourite Development Technolgies? 

### ISSUE THREAD

**Issue by sjohnston00** [thisdarktao/ama#1]
Feel free mention any that aren't your favourite as well 👍🏼

**Comment by adamhalesworth** [comment]
Hi @sjohnston00,

Since I'm primarily a mobile developer, Flutter is my most favourite bit of development tech right now. It's like a dream come true after working with Xamarin for at least 5 years. While Xamarin gets the job done, I found it pretty unreliable (does that count as a disliked tech?).

- My blog uses Gatsby, but I'm in the process of switching to Eleventy just to make it a bit lighter weight.
- In terms of front-end, I really like React and TypeScript, you can't really go wrong with that combo.
- For back-end my choice would _always_ be some kind of Linux stack (Ubuntu, CentOS).
- For APIs, I think 
- In a previous role we used Docker for pretty much all local web development and I loved it. It makes deployment so much easier.

If I think of any others I'll add them.
